apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: backend
spec:
  provider:
    gcpsm:
      projectID: "YOUR_PROJECT_ID"  # Replace with your GCP project ID
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: gke-autopilot-cluster
          serviceAccountRef:
            name: dev-backend-sa  # Kubernetes SA with Workload Identity annotation
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: database
spec:
  provider:
    gcpsm:
      projectID: "YOUR_PROJECT_ID"  # Replace with your GCP project ID
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: gke-autopilot-cluster
          serviceAccountRef:
            name: dev-database-sa  # Kubernetes SA with Workload Identity annotation
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: frontend
spec:
  provider:
    gcpsm:
      projectID: "YOUR_PROJECT_ID"  # Replace with your GCP project ID
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: gke-autopilot-cluster
          serviceAccountRef:
            name: dev-frontend-sa  # Kubernetes SA with Workload Identity annotation
