name: Terraform - Prod Deploy

on:
  push:
    tags: [ 'infra-v*' ]  # Trigger on tags like infra-v1.0.0
  workflow_dispatch:      # Allow manual trigger

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_PROD }}
  TF_VERSION: '1.5.7'
  WORKING_DIR: './terraform'

jobs:
  terraform-apply:
    name: Terraform Apply (Prod)
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    
    steps:
    - uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}
    
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ secrets.GCS_BUCKET_PROD }}"
    
    - name: Terraform Plan
      run: terraform plan -var-file="terraform-prod.tfvars.example" -out=tfplan
    
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
